export const themeSchema = {
  JersApp: {
    name: 'JersApp',
    main: '#242C3B',
    title: '#A7A5A5',
    subText: '#958C8C',
    headerText: 'white',
    appBar: '#151B26',
    model: '#2D3544',
    themeText: 'white',
    shadows: 'white',
    button: '#292929',
    tabBarIndicator: '#2F58A7',
    statusIndicator: '#0056FC',
    bubbleSenderBgColor: 'gray',
    bubbleReceiverBgColor: '#439BCC',
    bubbleTextColor: 'black',
    bubblesSubTextColor: 'gray',
  },
  Whatsapp: {
    name: 'Whatsapp',
    main: 'white',
    title: 'black',
    headerText: 'white',
    subText: 'black',
    appBar: '#008069',
    model: 'white',
    shadows: 'gray',
    themeText: '#008069',
    button: '#008069',
    tabBarIndicator: 'white',
    statusIndicator: '#008069',
    bubbleSenderBgColor: '#064e49',
    bubbleReceiverBgColor: '#064e49',
    bubbleTextColor: 'white',
    bubblesSubTextColor: 'slategray',
  },
  DarkMode: {
    name: 'DarkMode',
    main: 'black',
    title: 'white',
    subText: '#958C8C',
    headerText: 'white',
    appBar: '#0E0E0E',
    model: '#292929',
    themeText: 'white',
    shadows: 'red',
    button: '#292929',
    tabBarIndicator: 'white',
    statusIndicator: '#008069',
    bubbleSenderBgColor: 'slategray',
    bubbleReceiverBgColor: 'slategray',
    bubbleTextColor: 'white',
    bubblesSubTextColor: 'smokewhite',
  },
};
export const WhatsappThemeSchema = {
  main: 'white',
  title: 'black',
  headerText: 'white',
  subText: 'black',
  appBar: '#008069',
  model: 'white',
  shadows: 'gray',
  themeText: '#008069',
  button: '#008069',
};
export const DarkThemeSchema = {
  main: 'black',
  title: 'white',
  subText: '#958C8C',
  headerText: 'white',
  appBar: '#0E0E0E',
  model: '#292929',
  themeText: 'white',
  shadows: 'red',
  button: '#292929',
};
export const JersAppThemeSchema = {
  main: '#242C3B',
  title: '#A7A5A5',
  subText: '#958C8C',
  headerText: 'white',
  appBar: '#0D192E',
  model: '#2D3544',
  themeText: 'white',
  shadows: 'red',
  button: '#292929',
  tabBarIndicator: '#2F58A7',
  statusIndicator: '#0056FC',
};
